### ISSUE TITLE
Threat is always reset on feign death, even on resists

### ISSUE THREAD

**Issue by karlh1** [dfherr/LibThreatClassic2#31]
Hi,

during the last few raids I noticed my threat always resets to zero when casting feign death, even when it's resisted (RESISTED shows up on screen). This renders the threat meter unusable until the next feign death goes through.

On checking the source I discovered some code specific to hunters that is supposed to deal with this situation. But it seems that it's not working as intended. I tried to enable the debug mode (via /tc2 debug) and inserted some print()s into the code but no messages show up at all on /reload. Is there anything I can help with to debug this issue?

**Comment by dfherr** [comment]
Hi,

thanks for contributing and raising this issue! 

I added your suggestion (removing bonsu threat on misses) to the library and your merge request helped understanding the problem. However, I didn't merge this tho, as it contains errors (you used `v` instead of `k` in the loop) and only adds the functionality to one class instead of fixing the issue everywhere, but still added a version bump in the commit.

**Comment by dfherr** [comment]
this should be fixed in the next version.
